# Generated by Django 3.2.16 on 2023-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_alter_champion_passive_ability_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='ability_1_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='ability_2_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='ability_3_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='champion',
            name='ultimate_ability_description',
            field=models.TextField(),
        ),
    ]
